### ISSUE TITLE
is it possible to setup prometheus export without restart cassandra instances

### ISSUE THREAD

**Issue by zhihuiFan** [nabto/cassandra-prometheus#2]
by reading the README,  looks we have to restart the cassandra instance with the extra setting.  is it pssible to setup prometheus export without restart cassandra instances?    I used mongodb_exporter for MongoDB, it just work as a mongodb instance clients and no need to restart the mongodb instance.

**Comment by mkm85** [comment]
Probably not, you could use the prometheus jmx exporter if you need to get cassandra metrics to prometheus without restarting cassandra.
