### ISSUE TITLE
How to access the metrics from a Prometheus instance port / path?

### ISSUE THREAD

**Issue by VinceMD** [nabto/cassandra-prometheus#3]
I'm running Cassandra cluster in Kubernetes. Cassandra is in Docker.
We also already have an instance of Prometheus running.

what is the port/path Prometheus should connect to to scrape the metrics from Cassandra if we add this utility to the Cassandra docker? 

Is just port 7400 ?

**Comment by nabto** [comment]
it's just port 7400 and the path /metrics
